### ISSUE TITLE
missing DEFAULT_ENCODING in src/spi/binary/__init__.py

### ISSUE THREAD

**Issue by michael-at-mitxp** [Opendigitalradio/python-hybridspi#8]
We just ran the dump_binary script from the master branch with python 3.9 on Windows.
There is a little bug in src/spi/binary.
You are using a DEFAUT_ENCODING var, but never define or import it.
We just defined it next to DEFAULT_LANG in the src/spi/  module and it works fine.

**Comment by nickpiggott** [comment]
Hi

Thanks for letting me know, and for the fix. I've added it in the same place and updated the code

DEFAULT_ENCODING = "utf-8"
